name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t bmoregeo/ring-alarm-mqtt . --file Dockerfile --tag ring-alarm-mqtt:$(date +%s)
